# Generated by Django 2.2.1 on 2019-05-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190509_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.Review'),
        ),
    ]
