# Generated by Django 2.2 on 2019-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190509_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='pic_folder/FLAT-SEVAN-COVER.jpg', upload_to='C:/Users/User/Desktop/ProjectWebDev/back/EasyLib/api/pic_folder/'),
        ),
    ]
