# Generated by Django 2.2.1 on 2019-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190512_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='pic_folder/FLAT-SEVAN-COVER.jpg', upload_to='Users/User/Desktop/ProjectWebDev/back/EasyLib/api/pic_folder/'),
        ),
    ]
