# Generated by Django 2.2.1 on 2019-05-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='book',
            field=models.ManyToManyField(null=True, related_name='bookss', to='api.Book'),
        ),
    ]
