# Generated by Django 2.2.1 on 2019-05-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_book_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
