# Generated by Django 2.2.1 on 2019-05-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_delete_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.CharField(max_length=200),
        ),
    ]
